### ISSUE TITLE
test Issues

### ISSUE THREAD

**Issue by gbockus** [gbockus/jsForceInAction#1]

**Comment by gbockus** [comment]
add a comment

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by gbockus** [comment]
add a comment

**Comment by gbockus** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by gbockus** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "invalid access token",
    "errorType": "Error",
    "stackTrace": [
        "createChallenge (/var/task/index.js:128:22)",
        "exports.handler (/var/task/index.js:409:13)"
    ],
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by gbockus** [comment]
Failed to create challenge
Status code: 500
Response body:
```
"<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link rel='stylesheet' href='/stylesheets/style.css' />\n  </head>\n  <body>\n    <h1>Cannot read property &#x27;replace&#x27; of undefined</h1>\n<h2></h2>\n<pre>TypeError: Cannot read property &#x27;replace&#x27; of undefined\n    at module.exports (/app/node_modules/jwt-decode/lib/base64_url_decode.js:14:19)\n    at module.exports (/app/node_modules/jwt-decode/lib/index.js:10:21)\n    at fMassageV3Payload (/app/routes/index.js:70:17)\n    at /app/routes/index.js:280:23\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/app/node_modules/express/lib/router/route.js:110:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)\n    at /app/node_modules/express/lib/router/index.js:267:22\n    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)</pre>\n\n  </body>\n</html>\n"
```

**Comment by gbockus** [comment]
Failed to create challenge
Response body:
```
{
    "errorMessage": "An error occurred during JSON parsing",
    "errorType": "java.lang.RuntimeException",
    "stackTrace": [],
    "cause": {
        "errorMessage": "com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Long from String value 'ABC123': not a valid Long value\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@5f404594; line: 1, column: 16] (through reference chain: com.topcoder.direct.lambda.request.SaveDraftContestRequest[\"tcDirectProjectId\"])",
        "errorType": "java.io.UncheckedIOException",
        "stackTrace": [],
        "cause": {
            "errorMessage": "Can not construct instance of java.lang.Long from String value 'ABC123': not a valid Long value\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@5f404594; line: 1, column: 16] (through reference chain: com.topcoder.direct.lambda.request.SaveDraftContestRequest[\"tcDirectProjectId\"])",
            "errorType": "com.fasterxml.jackson.databind.exc.InvalidFormatException",
            "stackTrace": [
                "com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)",
                "com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:883)",
                "com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLong(StdDeserializer.java:454)",
                "com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:321)",
                "com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:303)",
                "com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)",
                "com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)",
                "com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)",
                "com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)",
                "com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)",
                "com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1441)",
                "com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1047)"
            ]
        }
    },
    "challengeURL": "https://www.topcoder-dev.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050401/?type=develop&noncache=true

**Comment by gbockus** [comment]
Failed to create challenge
Status code: 503
Response body:

```
"<!DOCTYPE html>\n    <html>\n    <head>\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n      <style type=\"text/css\">\n        html, body, iframe { margin: 0; padding: 0; height: 100%; }\n        iframe { display: block; width: 100%; border: none; }\n      </style>\n    <title>Application Error</title>\n    </head>\n    <body>\n      <iframe src=\"//s3.amazonaws.com/heroku_pages/error.html\">\n        <p>Application Error</p>\n      </iframe>\n    </body>\n    </html>"
```

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050403/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050404/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050405/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050406/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050407/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050408/?type=develop&noncache=true

**Comment by gbockus** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder-dev.com/challenge-details/30050409/?type=develop&noncache=true
